### ISSUE TITLE
TypeError: context.getScope is not a function

### ISSUE THREAD

**Issue by emaxx-google** [SebastienGllmt/eslint-plugin-no-floating-promise#16]
I'm experiencing the following error after ESLint got upgraded to 9.0.0:

```
TypeError: context.getScope is not a function
Occurred while linting /home/runner/work/chromeos_smart_card_connector/chromeos_smart_card_connector/common/js/src/async-asserts.js:36
Rule: "no-floating-promise/no-floating-promise"
    at ExpressionStatement > CallExpression (/home/runner/work/chromeos_smart_card_connector/chromeos_smart_card_connector/env/node_modules/eslint-plugin-no-floating-promise/lib/rules/no-floating-promise.js:148:58)
    at ruleErrorHandler (/home/runner/work/chromeos_smart_card_connector/chromeos_smart_card_connector/env/node_modules/eslint/lib/linter/linter.js:1145:48)
    at /home/runner/work/chromeos_smart_card_connector/chromeos_smart_card_connector/env/node_modules/eslint/lib/linter/safe-emitter.js:45:58
    at Array.forEach (<anonymous>)
    at Object.emit (/home/runner/work/chromeos_smart_card_connector/chromeos_smart_card_connector/env/node_modules/eslint/lib/linter/safe-emitter.js:45:38)
    at NodeEventGenerator.applySelector (/home/runner/work/chromeos_smart_card_connector/chromeos_smart_card_connector/env/node_modules/eslint/lib/linter/node-event-generator.js:297:26)
    at NodeEventGenerator.applySelectors (/home/runner/work/chromeos_smart_card_connector/chromeos_smart_card_connector/env/node_modules/eslint/lib/linter/node-event-generator.js:326:[22](https://github.com/GoogleChromeLabs/chromeos_smart_card_connector/actions/runs/8577666631/job/23510543074?pr=1144#step:5:23))
    at NodeEventGenerator.enterNode (/home/runner/work/chromeos_smart_card_connector/chromeos_smart_card_connector/env/node_modules/eslint/lib/linter/node-event-generator.js:340:14)
    at runRules (/home/runner/work/chromeos_smart_card_connector/chromeos_smart_card_connector/env/node_modules/eslint/lib/linter/linter.js:1184:40)
    at Linter._verifyWithoutProcessors (/home/runner/work/chromeos_smart_card_connector/chromeos_smart_card_connector/env/node_modules/eslint/lib/linter/linter.js:1453:31)
```

**Comment by SebastienGllmt** [comment]
Thanks for the bug report. I won't have time to make any updates to this project, but if somebody else wants to give it a go feel free to make a pull request

**Comment by emaxx-google** [comment]
BTW ESLint maintainers pointed me to this page describing breaking changes in 9.x: https://eslint.org/docs/latest/use/migrate-to-9.0.0#breaking-changes-for-plugin-developers

**Comment by SebastienGllmt** [comment]
Published 2.0.0
